### ISSUE TITLE
Cannot install and run project on Ubuntu and MacOS

### ISSUE THREAD

**Issue by nantille** [vidriotech/activity-viewer2#27]
Hello,

I followed the instructions in the Readme and on both platforms, the deamon could not be started with the provided commands so I tried python activity_viewer/app.py and then ran yarn start in the app folder on another tab. Even if the server seemed to start, the app could not connect to it.

Additionally, the web app doesn't show a menu bar on MacOS Firefox latest but it's there on Ubuntu 18 Firefox latest.

Any help regarding this is appreciated.

**Comment by aliddell** [comment]
Can you tell me what commands you ran and what errors you saw? I'm also surprised you were able to run the app in a browser, as the renderer process depends on Electron-specific code.

**Comment by nantille** [comment]
OK, I didn't see in your documentation that it relies on Electron-specific code.

I followed installation steps then I tried `viewerd` but apparently the alias didn't come with the install.
So on one tab I ran 
```python ./activity_viewer/app.py``` 

And on another
```
cd app
yarn start
```
All I got was a blank window from this yarn.

**Comment by aliddell** [comment]
Did you do a `pip install -e .` with the venv activated? That might be why `viewerd` doesn't work for you. Otherwise, I can't replicate this on Ubuntu (I don't have access to a Mac at the moment).

I should mention that it takes a little while for the app to build. Until you see something like `webpack built f629e8d27a4b025d7888 in 36973ms` at the bottom of your console, it's still building and you'll see the white screen until it's done:

![image](https://user-images.githubusercontent.com/844464/98711332-d99a7180-2352-11eb-8aa8-6785dda155ed.png)

I have a pretty fast PC so it might take even longer for you than the ~37s it took for me. The good news is that this Ubuntu machine is new, so while I couldn't put together a binary for the viewer before, I can try now.

**Comment by aliddell** [comment]
@nantille Did you ever get this working?

**Comment by nantille** [comment]
@aliddell Thanks for asking.

So I did `pip install -e .` as you said, and now I've got the viewerd available so I ran `viewerd start-daemon` and when I used `yarn start`, a blank window popped-up and maybe after 2-3min some UI appeared, and after 5min I got a mouse brain from Allen CCF v3.

Here's a screenshot that shows it running. So it's good to know that it works.
![activity_viewer](https://user-images.githubusercontent.com/10866779/100987365-baa48f00-354e-11eb-853e-b3b2bd0b94cb.png)

Tested on Ubuntu 18 and MacOS Mojave. I'm not sure why previously the blank window remained blank (meaning that the application failed to build or something like this).
